persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true

listener 1883
protocol mqtt
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true

max_queued_messages 10000
message_size_limit 268435456
set_tcp_nodelay true

autosave_interval 1800

allow_zero_length_clientid true
auto_id_prefix gw-

queue_qos0_messages false
persistent_client_expiration 1d

connection_messages true
sys_interval 10
